possible_precursors:
 - "4:2 FT"
 - "5:3 FT"
 - "6:2 FT"
 - "7:3 FT"
 - "8:2 FT"
 - "9:3 FT"
 - "10:2 FT"
 - "C4 ECF"
 - "C5 ECF"
 - "C6 ECF"
 - "C7 ECF"
 - "C8 ECF"
 - "C9 ECF"
 - "C10 ECF"
prior_name: "AFFF_impacted"